parameters:

services:
    _defaults:
        autowire: true     
        autoconfigure: true 

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'
            - '../src/Module/**/Entity/'
            - '../src/Module/**/Repository/'
            - '../src/Module/**/Service/'

    App\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
